fancybox: true ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: chris-an-emacser ## Your disqus_shortname, e.g. username
google_search: false ## Use Google search, true/false.
baidu_search: false ## Use Baidu search, true/false.
gitment:
  enable: false ## If you want to use Gitment comment system please set the value to true.
  owner: ## Your GitHub ID, e.g. username
  repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. imsun.github.io
  client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
uyan: ## Your uyan_id. e.g. 1234567
gentie: ## Your gentie_productKey, e.g. fc799538c7ad4cf5a5a0c2877a90cbd7
livere: ## Your livere data-uid, e.g. MTAyMC8zMDAxOC78NTgz
changyan: ## Your changyan appid, e.g. cyrALsXc8
changyan_conf: ## You changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b
google_search: true ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
toc_number: true ## If you want to add list number to toc please set the value to true.
shareto: false ## If you want to use the share button please set the value to true, you must have hexo-helper-qrcode installed.
busuanzi: false ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.
canvas_nest:
  enable: false ## If you want to use dynamic background please set the value to true, you can also fill the following parameters to customize the dynamic effect, or just leave them blank to keep the default effect.
  color: ## RGB value of the color, e.g. "100,99,98"
  opacity: ## Transparency of lines, e.g. "0.7"
  zIndex: ## The z-index property of the background, e.g. "-1"
  count: ## Quantity of lines, e.g. "150"
donate:
  enable: ture ## If you want to show the donate button after each post, please set the value to true and fill the following items according to your need. You can also enable donate button in a page by adding a "donate: true" item to the front-matter.
  github: ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
  alipay_qr: /img/AliPayQR.png ## Path of Alipay QRcode image, e.g. /img/AliPayQR.png
  wechat_qr: /img/WeChatQR.png ## Path of Wechat QRcode image, e.g. /img/WeChatQR.png
  btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
  btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
  paypal_url: ## Paypal URL, e.g. https://paypal.me/tufu9441

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: categories
    directory: categories/
    icon: fa-folder
  - page: Planet
    directory: planet-emacs-cn/
    icon: fa-user
  - page: 学术写作指要
    directory: essentials-of-academic-writing/
    icon: fa-book
  - page: Emacs-w64
    directory: emacs-w64/
    icon: fa-check
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - links

links:
  - title: 便宜好用的搬瓦工(含推广)
    url: https://bandwagonhost.com/aff.php?aff=3069
  - title: 支持小时收费的vultr (含推广)
    url: http://www.vultr.com/?ref=7184966
  - title: Emacsist
    url: http://emacsist.com/
  - title: 璀璨星空
    url: http://jerry011235.github.io/
  - title: GeekPlux
    url: http://www.geekplux.com/
  - title: lijigang
    url: http://www.lijigang.com/
  - title: codefalling
    url: http://codefalling.com/
  - title: 子龙山人
    url: http://zilongshanren.com/
  - title: Kelvin的胡言乱语
    url: http://kelvinh.github.io/
  - title: Emacs China
    url: http://emacs-china.org/
  # - title: 笔良文昌
  #   url: http://tian1.me/
  - title: 简单可依赖
    url: https://www.tiexo.cn/
  - title: Jet's Notes
    url: http://jetyu.me/
  - title: Raintone
    url: http://login926.top/
  - title: LAW GEEK
    url: http://lawgeek.info/
  - title: 计算化学公社(含推广)
    url: http://bbs.keinsci.com/?fromuid=4772
  - title: 狐吧
    url: http://tieba.baidu.com/f?kw=firefox&ie=utf-8
  - title: Chem_peng
    url: https://chempeng.github.io/
  - title: 瘫曲的Blog
    url: https://urzz.me/

# timeline:
#   - num: 1
#     word: 2014/06/12-Start
#   - num: 2
#     word: 2014/11/29-XXX
#   - num: 3
#     word: 2015/02/18-DDD
#   - num: 4
#     word: More

# Static files
js: js
css: css

# Theme version
version: 0.0.0
